# Generated by Django 3.0.4 on 2020-03-11 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mess_name', models.CharField(max_length=200)),
                ('timing', models.TimeField()),
                ('address', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_time', models.IntegerField()),
                ('monthly', models.IntegerField()),
                ('mess_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess.Mess')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=200)),
                ('mess_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess.Mess')),
            ],
        ),
    ]
