# Generated by Django 3.0.4 on 2020-03-16 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.Record')),
                ('Shop_Name', models.CharField(blank=True, max_length=30)),
                ('Address', models.CharField(blank=True, max_length=150)),
            ],
            bases=('register.record',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.Record')),
                ('College', models.CharField(blank=True, max_length=40)),
                ('Stay', models.CharField(blank=True, max_length=150)),
            ],
            bases=('register.record',),
        ),
    ]
